name: 'Generate coverage report'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  coverage:

    runs-on: [ubuntu-latest]
    name: Coverage on Ubuntu

    steps:
      - uses: actions/checkout@v3.0.2
      - name: Set up JDK 11
        uses: actions/setup-java@v3.5.1
        with:
          distribution: 'temurin'
          java-version: '11'
          check-latest: true
      - name: Generate coverage with JaCoCo
        run: mvn -V --color always -ntp clean verify --file pom.xml '-Dgpg.skip'
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
